Add DynamoDB limiter backends
mennanov/limiters pull request #10
Opened 2023-03-16 15:57 UTC by lamebear

This adds support to use DynamoDB as a Limiter backend for:

* FixedWindow
* SlidingWindow
* LeakyBucket
* TokenBucket

2023-03-17 02:43 UTC, mennanov commented
The tests are failing for me even locally:

```
=== RUN   TestBucketTestSuite/TestTokenBucketRealClock
    tokenbucket_test.go:119: 
        	Error Trace:	/Users/renat/projects/limiters/tokenbucket_test.go:119
        	Error:      	Max difference between 3 and 1 allowed is 1, but difference was 2
        	Test:       	TestBucketTestSuite/TestTokenBucketRealClock
        	Messages:   	{capacity:5 refillRate:100000000 requestCount:10 requestRate:25000000 missExpected:3 delta:1}
    tokenbucket_test.go:119: 
        	Error Trace:	/Users/renat/projects/limiters/tokenbucket_test.go:119
        	Error:      	Max difference between 3 and 1 allowed is 1, but difference was 2
        	Test:       	TestBucketTestSuite/TestTokenBucketRealClock
        	Messages:   	{capacity:5 refillRate:100000000 requestCount:10 requestRate:25000000 missExpected:3 delta:1}
    tokenbucket_test.go:119: 
        	Error Trace:	/Users/renat/projects/limiters/tokenbucket_test.go:119
        	Error:      	Max difference between 3 and 1 allowed is 1, but difference was 2
        	Test:       	TestBucketTestSuite/TestTokenBucketRealClock
        	Messages:   	{capacity:5 refillRate:100000000 requestCount:10 requestRate:25000000 missExpected:3 delta:1}
    tokenbucket_test.go:119: 
        	Error Trace:	/Users/renat/projects/limiters/tokenbucket_test.go:119
        	Error:      	Max difference between 2 and 0 allowed is 1, but difference was 2
        	Test:       	TestBucketTestSuite/TestTokenBucketRealClock
        	Messages:   	{capacity:10 refillRate:100000000 requestCount:15 requestRate:33000000 missExpected:2 delta:1}
    tokenbucket_test.go:119: 
        	Error Trace:	/Users/renat/projects/limiters/tokenbucket_test.go:119
        	Error:      	Max difference between 2 and 0 allowed is 1, but difference was 2
        	Test:       	TestBucketTestSuite/TestTokenBucketRealClock
        	Messages:   	{capacity:10 refillRate:100000000 requestCount:15 requestRate:33000000 missExpected:2 delta:1}
    tokenbucket_test.go:119: 
        	Error Trace:	/Users/renat/projects/limiters/tokenbucket_test.go:119
        	Error:      	Max difference between 2 and 0 allowed is 1, but difference was 2
        	Test:       	TestBucketTestSuite/TestTokenBucketRealClock
        	Messages:   	{capacity:10 refillRate:100000000 requestCount:15 requestRate:33000000 missExpected:2 delta:1}
    tokenbucket_test.go:119: 
        	Error Trace:	/Users/renat/projects/limiters/tokenbucket_test.go:119
        	Error:      	Max difference between 2 and 0 allowed is 1, but difference was 2
        	Test:       	TestBucketTestSuite/TestTokenBucketRealClock
        	Messages:   	{capacity:10 refillRate:100000000 requestCount:16 requestRate:33000000 missExpected:2 delta:1}
    tokenbucket_test.go:119: 
        	Error Trace:	/Users/renat/projects/limiters/tokenbucket_test.go:119
        	Error:      	Max difference between 2 and 0 allowed is 1, but difference was 2
        	Test:       	TestBucketTestSuite/TestTokenBucketRealClock
        	Messages:   	{capacity:10 refillRate:100000000 requestCount:16 requestRate:33000000 missExpected:2 delta:1}
    tokenbucket_test.go:119: 
        	Error Trace:	/Users/renat/projects/limiters/tokenbucket_test.go:119
        	Error:      	Max difference between 2 and 0 allowed is 1, but difference was 2
        	Test:       	TestBucketTestSuite/TestTokenBucketRealClock
        	Messages:   	{capacity:10 refillRate:100000000 requestCount:16 requestRate:33000000 missExpected:2 delta:1}
    tokenbucket_test.go:119: 
        	Error Trace:	/Users/renat/projects/limiters/tokenbucket_test.go:119
        	Error:      	Max difference between 2 and 0 allowed is 1, but difference was 2
        	Test:       	TestBucketTestSuite/TestTokenBucketRealClock
        	Messages:   	{capacity:10 refillRate:100000000 requestCount:16 requestRate:33000000 missExpected:2 delta:1}
```

I'd suggest checking the implementation of `TokenBucketDynamoDB`

2023-03-17 02:49 UTC, mennanov commented
You may try to run just 1 test case at a time in `TestTokenBucketRealClock` and see how the state of the token bucket is persisted in DynamoDB: examine the state before the test and after and see if it is correct.

2023-03-17 03:08 UTC, mennanov requested changes

2023-03-17 03:08 UTC, mennanov commented on leakybucket.go
> +func (t LeakyBucketDynamoDB) getGetItemInput() *dynamodb.GetItemInput {
Struct LeakyBucketDynamoDB has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation. 

Consider changing the signature to:

```golang
func (t *LeakyBucketDynamoDB) getGetItemInput() *dynamodb.GetItemInput
```

Same applies to other methods with non-pointer receivers (e.g. `loadStateFromDynamoDB`).

2023-03-17 03:08 UTC, mennanov commented on tokenbucket.go
> +	leakyBucket *LeakyBucketDynamoDB
It feels a little weird that the `leakyBucket` struct is reused here. 
Consider creating its own struct fields and methods here without reusing the leakyBucket implementation (it will result in more lines of code, but a better structured code overall)

2023-03-17 03:08 UTC, mennanov commented on tokenbucket.go
> +func (t TokenBucketDynamoDB) getPutItemInputFromState(state TokenBucketState) *dynamodb.PutItemInput {
Struct TokenBucketDynamoDB has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation.

2023-03-17 03:08 UTC, mennanov commented on tokenbucket.go
> +// TokenBucketDynamoDB is a DyanamoDB implementation of a TokenBucketStateBackend.
```suggestion
// TokenBucketDynamoDB is a DynamoDB implementation of a TokenBucketStateBackend.
```

2023-03-17 03:08 UTC, mennanov commented on slidingwindow.go
> +	fixedWindow *FixedWindowDynamoDB
I think it will be clearer if the `FixedWindowDynamoDB` is not reused here. Instead add sliding window specific fields and methods.

2023-03-17 03:08 UTC, mennanov commented on dynamodb.go
> +var lock *sync.Mutex = &sync.Mutex{}
Types can be omitted 

```suggestion
var tableCache = make(map[string]DynamoDBTableProperties)
var lock = &sync.Mutex{}
```

2023-03-17 03:08 UTC, mennanov commented on dynamodb.go
> +// DynamoDBTableProperties are supplied to DynamoDB limiter backends
Please add more details why this struct is needed

2023-03-17 16:32 UTC, lamebear commented
I was able to replicate the failures on an AMD64 system but not on my Mac M2

2023-03-18 23:01 UTC, lamebear commented
@mennanov all tests are passing. Changed the docker image from `localstack` to  `dynamodb-local`.

2023-03-18 23:19 UTC, closed without merging